# Generated by Django 5.0.14 on 2026-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bio',
            field=models.TextField(blank=True, help_text='Short description about the vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tin_number',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=100),
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendors',
        ),
    ]
