# Generated by Django 5.0.14 on 2026-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Profile picture URL of the delivery agent', max_length=500),
        ),
    ]
