# Generated by Django 5.0.14 on 2026-04-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_order_options_rename_total_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('express', 'Express (1-2 hrs)'), ('scheduled', 'Scheduled')], default='express', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
